[project]
name = "aeventkit"
version = "2.1.0"
description = "Event-driven data pipelines"
readme = "README.rst"
requires-python = ">=3.11"
license = "BSD-3-Clause"
authors = [{ name = "Ewald R. de Wit" }]
keywords = ["python", "asyncio", "event", "driven", "data", "pipelines"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/ib-api-reloaded/eventkit"
Repository = "https://github.com/ib-api-reloaded/eventkit"
"Bug Tracker" = "https://github.com/ib-api-reloaded/eventkit/issues"

[project.optional-dependencies]
numpy = ["numpy (>=2.4.4,<3.0.0)"]

[dependency-groups]
dev = [
    "ruff>=0.15.9,<0.16.0",
    "pre-commit>=3.5.0,<4.0.0",
    "pytest>=8.4.1,<9.0.0",
    "pytest-xdist>=3.6.1,<4.0.0",
    "mypy>=1.20.0,<2.0.0",
    "pytest-cov>=6.2.1,<7.0.0",
    "pytest-asyncio>=1.0.0,<2.0.0",
]
docs = [
    "sphinx-autodoc-typehints>=2.0.0,<3.0.0",
    "sphinx-rtd-theme>=2.0.0,<3.0.0",
    "myst-parser>=2.0.0,<3.0.0",
    "sphinxcontrib-napoleon>=0.7,<0.8",
]

[tool.poetry]
# Because we renamed the pypi top-level package to `aeventkit` but we still want to `import eventkit`
# we need to have `packages` for `eventkit` so it can find it with our _name_ being `aeventkit` now.
packages = [{ include = "eventkit" }]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.9"
pre-commit = "^3.5.0"
pytest = "^8.4.1"
pytest-xdist = "^3.6.1"
mypy = "^1.20.0"
pytest-cov = "^6.2.1"
pytest-asyncio = "^1.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx-autodoc-typehints = "^2.0.0"
sphinx-rtd-theme = "^2.0.0"
myst-parser = "^2.0.0"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = [
    "D100",
    "D101",
    "D102",
    "D105",
    "D107",
    "D200",
    "D205",
    "D400",
    "D401",
    "D402",
    "E402",
    "F401",
]
[tool.pytest.ini_options]
log_cli = true
asyncio_default_test_loop_scope = "session"

[[tool.mypy.overrides]]
module = ["numpy"]
ignore_missing_imports = true
