name: Build 🛠️ and test 🧪 eventkit

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [pypy3.10, "3.10", "3.11", "3.12"]

        steps:
          - uses: actions/checkout@v4
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}
                cache: pip
                # Print the current Python version
          - name: Display Python version
            run: python -c "import sys; print(sys.version)"
          - name: Install dependencies
            run: |
                python -m pip install -U pip poetry
                poetry install --with dev

          - name: Ruff static code analysis
            run: |
                poetry run ruff check eventkit/
                poetry run ruff format eventkit/

          - name: MyPy static code analysis
            run: |
                poetry run mypy .

          - name: Test with pytest
            run: |
                poetry run pytest -vs

          - name: Build a binary wheel and a source tarball
            run: |
                poetry build -n
