name: eventkit

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pip poetry -U
          poetry install --with dev

      - name: Ruff static code analysis
        run: |
          poetry run ruff check eventkit/
          poetry run ruff format eventkit/

      - name: MyPy static code analysis
        run: |
          poetry run mypy .

      - name: Test with pytest
        run: |
          poetry run pytest -vs
